'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BDTCLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AddPolyLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddPolyLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AddSymbol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddSymbol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Arc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bando() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bando", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property closedcurve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closedcurve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property curve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DauKyHieu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DauKyHieu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FillDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FillDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FillUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FillUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GoToNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoToNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GoToPrevious() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoToPrevious", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MuiTen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MuiTen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MuiTenDon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MuiTenDon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MuiTenHo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MuiTenHo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MuiTenNho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MuiTenNho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewDT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property polygon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("polygon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property progbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rectangle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rectangle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property REDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ruler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ruler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SongSong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SongSong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SongSongKin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SongSongKin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UNDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoom1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoom1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoomin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoomin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zoomout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zoomout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
